version: '3'

services:
    nginx:
      image: nginx:1.19.8-alpine
      working_dir: /etc/nginx
      volumes:
        - ./src/public:/var/www/html/public
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - '9000:80'
      depends_on:
        - php-fpm

    php-fpm:
      build: ./docker/php-fpm
      working_dir: /var/www/html
      depends_on:
        - postgres
      volumes:
        - ./src:/var/www/html
        - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/xxx-devilbox-default-php.ini
      environment:
        - NEW_UID
        - NEW_GID
      
    postgres:
      image: postgres:13
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      volumes:
        - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:


